import pygame

# Инициализация шрифтов
pygame.font.init()

# ЦВЕТА
COLOR_GRAY = (211, 211, 211)
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)

# ШРИФТЫ
FONT_STANDARD = 'Calibri'
FONT_SIZE_BIG = 24
FONT_SIZE_MIDDLE = 18
FONT_SIZE_SMALL = 16

# РАЗМЕРЫ ОКНА ПРИЛОЖЕНИЯ
WINDOW_WIDTH = 1440
WINDOW_HEIGHT = 900

# РАЗМЕРЫ КНОПОК ОКНА
BUTTON_CLOSE_SIZE = 24
BUTTON_MINIMIZE_SIZE = 24
BUTTON_MARGIN = 6

# РАЗМЕРЫ ПОЛЯ ВВОДА
TEXT_INPUT_HEIGHT = 30

# РАЗМЕРЫ ЧЕКБОКСА
CHECKBOX_SIZE = 30
CHECKBOX_INNER_SIZE = 25
CHECKBOX_OFFSET = 5

# РАЗМЕРЫ ПОЛОСЫ ПРОКРУТКИ
SCROLLBAR_BORDER_SIZE = 20
SCROLLBAR_DECOR_OFFSET = 6
SCROLLBAR_CIRCLE_DIAMETER = 14
SCROLLBAR_MIN_LENGTH = 66

# РАЗМЕРЫ КНОПКИ COPY DNA
COPY_DNA_BUTTON_WIDTH = 30
COPY_DNA_BUTTON_HEIGHT = 20
COPY_DNA_LINE_THICKNESS = 6
COPY_DNA_LINE_SPACING = 6

# МАРГИНЫ ДЛЯ КНОПОК
BUTTON_MARGIN_DEFAULT = (12, 12, 3, 3)

# СПИСОК КНОПОК ЛЕНТЫ
BUTTON_RIBBON_NAMES = [
    'VITALS', 'BODY', 'SHOES/GEAR', 'ACCESSORIES', 'ATTRIBUTES',
    'TENDENCIES', 'HOT ZONES', 'SIGNATURE', 'CONTRACT', 'BADGES'
]

# ПОЗИЦИИ ЭЛЕМЕНТОВ
LINE_1_START = (250, 0)
LINE_1_END = (250, 900)
LINE_2_START = (610, 0)
LINE_2_END = (610, 900)

SEARCH_LABEL_POS = (275, 15)
SEARCH_INPUT_POS = (275, 47)
SEARCH_INPUT_LENGTH = 300

TEXT_FIELD_POS = (275, 100)
TEXT_FIELD_SIZE = (300, 770)

SCROLLBAR_VERT_POS = (581, 100)
SCROLLBAR_VERT_LENGTH = 770
SCROLLBAR_VERT_LINES = 50

BUTTON_RIBBON_POS = (624, 47)
BUTTON_RIBBON_SIZE = (776, 30)
SCROLLBAR_HORIZ_POS = (624, 47)
SCROLLBAR_HORIZ_LENGTH = 776

COPY_DNA_BUTTON_POS = (1404, 875)